<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/urn/urn.glb --transform
Author: Weekless (https://sketchfab.com/weekless)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/urn-7a066694c3724cff9b9ee585d65385f5
Title: Urn
-->

<script>
  import {Group, MeshBasicMaterial} from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import {useSuspense, useGltf, useTexture} from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/urn/urn-transformed.glb', { useDraco: true }))

  const component = forwardEventHandlers()

  const texture = suspend(useTexture('/models/urn/material_baseColor-min.png'))
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf then gltf}
    {#await texture then tex}
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={1.4} position={[0, -1.5, 0]}>
        <T.Mesh
                geometry={gltf.nodes.Object_4.geometry}
                material={new MeshBasicMaterial({ map: tex })}
                rotation={[Math.PI / 2, 2.5, 0]}
        />
      </T.Group>
    {/await}
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
