<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/urn/urn.glb --transform
Title: Urn
-->

<script>
  // Importing necessary components and libraries
  import {Group, MeshBasicMaterial} from 'three' // Three.js components for 3D object and material
  import { T, forwardEventHandlers } from '@threlte/core' // Core components and utilities from threlte
  import {useSuspense, useGltf, useTexture} from '@threlte/extras' // Extra utilities from threlte for handling suspense, GLTF and textures

  // Creating a new Group object
  export const ref = new Group()

  // Using the suspense hook from threlte extras
  const suspend = useSuspense()

  // Using the GLTF hook from threlte extras to load a GLTF model with Draco compression
  const gltf = suspend(useGltf('/models/urn/urn-transformed.glb', { useDraco: true }))

  // Forwarding event handlers
  const component = forwardEventHandlers()

  // Using the texture hook from threlte extras to load a texture
  const texture = suspend(useTexture('/models/urn/material_baseColor-min.png'))
</script>

<!-- Svelte component markup -->
<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  <!-- Waiting for the GLTF model to load -->
  {#await gltf then gltf}
    <!-- Waiting for the texture to load -->
    {#await texture then tex}
      <!-- Creating a Group component with specific rotation, scale and position -->
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={1.4} position={[0, -1.5, 0]}>
        <!-- Creating a Mesh component with the geometry from the GLTF model and a basic material with the loaded texture -->
        <T.Mesh
                geometry={gltf.nodes.Object_4.geometry}
                material={new MeshBasicMaterial({ map: tex })}
                rotation={[Math.PI / 2, 2.5, 0]}
        />
      </T.Group>
    {/await}
  {:catch error}
    <!-- Displaying an error slot if there's an error -->
    <slot name="error" {error} />
  {/await}

  <!-- Displaying a slot with the ref -->
  <slot {ref} />
</T>